my_snowflake_project:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: yrfhcnw-jn59694

      # User/password auth
      user: stankusnt
      password: Littletroll7712

      role: ACCOUNTADMIN
      database: STG
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False
      query_tag: #dbt

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)