USE DATABASE snowflake_sample_data;

USE SCHEMA TPCH_SF1000;

CREATE TABLE Customer_orders AS 

SELECT *
FROM LINEITEM
LEFT JOIN ORDERS ON LINEITEM.L_ORDERKEY = Orders.O_ORDERKEY
WHERE O_ORDERPRIORITY = '1-URGENT'